
import java.util.Scanner;

public class guess {

	public static void guessTheNumbergame()
	{
	
		Scanner sc = new Scanner(System.in);

		
		int number = 1 + (int)(100
							* Math.random());

	 System.out.println("Enter the number of trials till which you want to play:");
     int trial=sc.nextInt();

		int i, guess;

		System.out.println(
			"So in our Game which is developed by Anish G Raj, the system will generate a random number"
			+ " between 1 to 100."
			+ "and you have to guess the number"
			+ " within" +" "+trial+" "+ "trials.");

	
		for (i = 0; i < trial; i++) {

			System.out.println(
				"Guess the number:");
			guess = sc.nextInt();
			

			if (number == guess) {
				System.out.println(
					"Congratulations!"
					+ " You won the Game, the number guessed by you is correct :)");
				break;
			}
			else if (number > guess
					&& i != trial - 1) {
				System.out.println(
					"The number is "
					+ "greater than " + guess+" please think of a greater number");
			}
			else if (number < guess
					&& i != trial - 1) {
				System.out.println(
					"The number is"
					+ " less than " + guess+" please think of a lesser number");
			}
		}

		if (i == trial) {
			System.out.println(
				"Game Over"
				+ " Try Again :(");

			System.out.println(
				"The number generated by the system was " + number);
		}
	}

	
	public static void main(String arg[])
	{
		guessTheNumbergame();
	}
}
